## Logistic regression 

- is a classification model that is very easy to implement but performs very
  well on linearly separable classes..


- It is one of the most widely used algorithm for classification


- It is also a linear model for binary classification that can be extended to multiclass
  classification via OvR(One vs Rest) technique
    
    
- used to predict the probability of a categorical dependent variable. In logistic regression, the dependent variable is a binary variable that contains data coded as 1 (yes, success, etc.) or 0 (no, failure, etc.).

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris=load_iris()

In [3]:
X = iris.data[:100]
y = iris.target[:100]

In [4]:
X.shape

(100, 4)

In [5]:
import numpy as np

In [6]:
np.unique(y)

array([0, 1])

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=10,random_state=1)

In [9]:
X_train.shape

(90, 4)

In [10]:
X_test.shape

(10, 4)

In [11]:
log = LogisticRegression()
log.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
log.intercept_[0]

-0.2686234961505791

In [21]:
log.score(X_test,y_test)

1.0

In [20]:
log.coef_[0]

array([-0.41681344, -1.41440264,  2.17945356,  0.99789544])

In [22]:
X_test[0]

array([5.5, 2.4, 3.8, 1.1])

In [23]:
def line(x1,x2,x3,x4):
    y=log.intercept_[0]+log.coef_[0][0]*x1+log.coef_[0][1]*x2+log.coef_[0][2]*x3+log.coef_[0][3]*x4
    
    return y

In [24]:
def prob(x1,x2,x3,x4):
    value = line(x1,x2,x3,x4)
    
    return 1/(1+np.exp(-value))

In [29]:
t=X_test[1]

In [30]:
t

array([5.4, 3. , 4.5, 1.5])

In [31]:
prob(t[0],t[1],t[2],t[3])

0.9894576887458335

### Probability is greater than 50%, it means sample(t) belongs to class 1

In [34]:
y_test[1]

1

#### now use predict method

In [ ]:
pred = log.predict(X_test)

In [ ]:
X_test[0].reshape(1,-1).ndim

In [ ]:
log.predict_proba(X_test[0].reshape(1,-1))

In [ ]:
y_test

In [ ]:
pred

In [35]:
import pandas as pd

In [36]:
data = pd.read_csv('dataset/data.csv',header=None)

In [37]:
data.columns=['Pregnancies','Glucose','BloodPressure','SkinThickness' ,
              'Insulin' ,'BMI' ,'DiabetesPedigreeFunction' ,'Age','Outcome']

In [38]:
data.head(2)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0

In [ ]:
data.shape

In [ ]:
data.Outcome.value_counts()

#### data we have is imbalance

In [ ]:
X = data.loc[:,['Glucose', 'BMI', 'Age']].values

y = data['Outcome'].values

In [ ]:
X.shape

In [ ]:
y.shape

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,random_state=1)

In [ ]:
log1=LogisticRegression()
log1.fit(X_train,y_train)

In [ ]:
log1.coef_

In [ ]:
log1.intercept_

In [ ]:
pred = log1.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix

In [ ]:
accuracy_score(y_test,pred)

In [ ]:
confusion_matrix(y_test,pred)

In [ ]:
np.bincount(y_test)

In [ ]:
np.unique(y_test)

In [ ]:
c=[.01,.1,10,100,1000]

for i in c:
    log2=LogisticRegression(C=i)
    log2.fit(X_train,y_train)
    print ('testing:',log2.score(X_test,y_test))