## Array arithmetic operations

In [1]:
#array must be same size
import numpy as np

In [2]:
a=np.array([1,2,3],int)
b=np.array([5,6,7],int)


In [3]:
v=a.astype(float)
v

array([ 1.,  2.,  3.])

In [4]:
print a+b
print a-b
print a*b
print b/a
print b**a
print b**2

[ 6  8 10]
[-4 -4 -4]
[ 5 12 21]
[5 3 2]
[  5  36 343]
[25 36 49]


In [5]:
c=np.array([[1,2],[3,4]])
d=np.array([[2,0],[1,3]])

In [6]:
c*d

array([[ 2,  0],
       [ 3, 12]])

In [7]:
print c
d

[[1 2]
 [3 4]]


array([[2, 0],
       [1, 3]])

In [8]:
np.dot(c,d)

array([[ 4,  6],
       [10, 12]])

In [9]:
c

array([[1, 2],
       [3, 4]])

In [10]:
for i in c:
    print i

[1 2]
[3 4]


In [11]:
for i,x in c:
    print i,x

1 2
3 4


In [12]:
c.prod()

24

In [13]:
k=np.array([[2,1,8],[9,1,12],[22,71,28]])
k

array([[ 2,  1,  8],
       [ 9,  1, 12],
       [22, 71, 28]])

In [30]:
k[1,2]=100
print k
#print k.max(axis=1)
k.sum(axis=1)
#k.argmax()
#k[0].argmax()
k[:,1].max()
#k[:,-1].max()
#k[0].sum()
#k[2,1]

[[  2   1   8]
 [  9   1 100]
 [ 22  71  28]]


71

In [31]:
#find min & max
a=np.array([2,1,8],float)
print 'index_number:value'
print a.argmin(),':',a.min()
print a.argmax(),':',a.max()


index_number:value
1 : 1.0
2 : 8.0


In [34]:
f=np.array([[5,2],[1,-1],[3,5]])
print f.shape
print f
f=f.reshape(2,3)

(3L, 2L)
[[ 5  2]
 [ 1 -1]
 [ 3  5]]


In [35]:
f

array([[ 5,  2,  1],
       [-1,  3,  5]])

In [36]:
print f[0]

[5 2 1]


In [37]:
f[0].sort()

In [43]:
f


array([[ 1,  2,  5],
       [-1,  3,  5]])

In [ ]:
z=np.arange(1,10,2)
z

In [44]:
s=np.array([[14,13],[6,5]])
s

array([[14, 13],
       [ 6,  5]])

In [45]:
s.sort(axis=0)

In [46]:
s

array([[ 6,  5],
       [14, 13]])

In [ ]:
v=np.array([[4,1,5],[8,9,3]])
v

In [ ]:
v[0].sort()

In [ ]:
v

In [ ]:
print 'min:',v.min(axis=1)  # will seek in row 1 & row 2

In [ ]:
print v.min(axis=0) # will seek in col 1 ,2& 3

In [ ]:
f

In [ ]:
# sorting in array

y=np.array([6,2,1,5,3],int)
y.sort()
print y,type(y)
p=np.array(sorted(y,reverse=True))
p,type(p)

In [47]:
# unique
u=np.array([1,1,2,2,2,4,4,4,4])
print np.unique(u)
#u.sort()

#print np.bincount(u)

[1 2 4]


In [ ]:
from sklearn.datasets import load_iris
iris=load_iris()


In [ ]:
X=iris.data
y=iris.target

In [ ]:
#y

In [ ]:
print np.unique(y)
print np.bincount(y)


In [ ]:
#extracted diagonal
d=np.array([[1,2,3],[3,4,5],[6,7,7]],int)
print d
print d.diagonal()
np.diag(d)

In [ ]:
#The any and all operators can be used to determine
#whether or not any or all elements of a Boolean array are
#true
c=np.array([False,True,False])
print any(c)
print all(c)
#c.all()
#c.any()


In [ ]:
k

In [ ]:

k[:,2][k[:,2]>25]

In [59]:
#where
g=np.arange(10,20)

print g
print np.where(g>15)
#print g[g>15]

print g[np.where(g>17)]
#g[g>17]
#g[[6,7]]

[10 11 12 13 14 15 16 17 18 19]
(array([6, 7, 8, 9], dtype=int64),)
[18 19]


In [53]:
f=np.array([1,7,8],int)
print np.where(f>1)#return indices if only condition is given

(array([1, 2], dtype=int64),)


In [60]:
# if condition is true return element will return
#from x ,otherwise from y
f2=np.array([3,5,6,4,9])
print np.where(f2>4,1,0)
print f2[f2>4]


[0 1 1 0 1]
[5 6 9]


In [65]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print a
a.mean(axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 4.,  5.,  6.])

In [63]:
#array selectors to filter specfic subset

h=np.array([[6,4],[5,9]],float)
#print h>=6 #return boolean values
print h[h>=6]
print h

[ 6.  9.]
[[ 6.  4.]
 [ 5.  9.]]


In [68]:
#median
med=np.array([1,4,5,8,9,2,3,60,100,6],float)

print 'median:',np.median(med)
#med.sort()
#print med
np.mean(med)

median: 4.5


9.8000000000000007

In [ ]:
med1=np.array([[30,65,70],[80,95,10],[50,90,60]])
print med1

In [ ]:
print np.median(med1)
print np.median(med1,axis=0)
print np.median(med1,axis=1)

In [ ]:
#mean

m1=np.array([1,2,3,4,5])
print 'mean:',np.mean(m1)

m2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print m2
print np.mean(m2,axis=0)

In [ ]:
#power()

p1=np.array([1,2,3],int)
print np.power(p1,2)
print p1**2

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a

In [ ]:
c=a[-2:,-2:]

In [ ]:
a[-2:,-3:-1]

In [ ]:
a

In [ ]:
#a[-2::-1,1:]
#a[:2,1:][-1::-1]
